global using Microsoft.Extensions.Options;
global using MongoDB.Driver;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Text.Json;
global using System.Threading.Tasks;
global using StackExchange.Redis;
